import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Izet Delibasic - Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-full bg-black min-h-screen py-2 lg:py-10 overflow-x-hidden px-6 lg:px-12 xl:px-20 text-gray-200'>{children}</div>
      </body>
    </html>
  )
}
